apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: exams
  name: exams
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: exams
  type: ClusterIP
