apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: about
  name: about
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: about
  type: ClusterIP

