apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: home
  name: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: home
    spec:
      containers:
      - image: amiharsh/msvc:home
        name: home
        env:
        - name: AUTH_URI
          value: "auth.example.com"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        resources: {}
status: {}
