apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: about
  name: about
spec:
  replicas: 1
  selector:
    matchLabels:
      app: about
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: about
    spec:
      containers:
      - image: aakashgaur57/about
        name: about
        resources: {}
status: {}
