apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-html-ingress
  namespace: html
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: msvc.delvex.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: home
            port:
              number: 80
      - path: /courses
        pathType: Prefix
        backend:
          service:
            name: courses
            port:
              number: 80
      - path: /about
        pathType: Prefix
        backend:
          service:
            name: about
            port:
              number: 80
      - path: /contact
        pathType: Prefix
        backend:
          service:
            name: contact
            port:
              number: 80
      - path: /exams
        pathType: Prefix
        backend:
          service:
            name: exams
            port:
              number: 80
      - path: /auth/login
        pathType: Prefix
        backend:
          service:
            name: login
            port:
              number: 80
      - path: /auth/register
        pathType: Prefix
        backend:
          service:
            name: login
            port:
              number: 80
  tls:
  - hosts:
    - msvc.delvex.io
    secretName: msvc-secret