apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: aakashgaur57/nodeapp
        name: backend
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: MONGO_URI
          value: "mongodb://mongo.msvc.svc.cluster.local:27017/mydb"
        resources: {}
status: {}
